id: P005363
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:46:20.943662
source_metadata:
  id: bdr:W29011
  title: ཞེ་སའི་ལག་དེབ་བློ་གསར་དགའ་སྟོན
  author: ''
  volumes:
    04b7a63d729044c1ad0c3090b9f74d25:
      image_group_id: I5017
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
